# Test Secrets for Secret Rotation Operator
---
# Secret 1: Already expired (for testing immediate alerts)
apiVersion: v1
kind: Secret
metadata:
  name: expired-secret-key
  namespace: default
  annotations:
    secret-operator.example.com/expires-at: "2024-01-01"
    secret-operator.example.com/warn-before: "7d"
  labels:
    managed-by: secret-operator
type: Opaque
data:
  secret-key: bXktZXhwaXJlZC1zZWNyZXQta2V5LTEyMzQ1Cg==

---
# Secret 2: Expiring soon within warning period
apiVersion: v1
kind: Secret
metadata:
  name: expiring-soon-credentials
  namespace: default
  annotations:
    secret-operator.example.com/expires-at: "2025-02-01"
    secret-operator.example.com/warn-before: "30d"
  labels:
    managed-by: secret-operator
type: Opaque
data:
  username: YWRtaW4=
  password: c2VjcmV0MTIz

---
# Secret 3: Valid for a long time should not trigger warnings
apiVersion: v1
kind: Secret
metadata:
  name: long-lived-certificate
  namespace: default
  annotations:
    secret-operator.example.com/expires-at: "2030-12-31"
    secret-operator.example.com/warn-before: "30d"
  labels:
    managed-by: secret-operator
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCmR1bW15LWNlcnRpZmljYXRlLWRhdGEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCmR1bW15LXByaXZhdGUta2V5LWRhdGEKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==

---
# Secret 4: No expiration annotation should be ignored by operator
apiVersion: v1
kind: Secret
metadata:
  name: unmanaged-secret
  namespace: default
  labels:
    note: "This secret has no expiration annotation and should be ignored"
type: Opaque
data:
  some-data: c29tZS1kYXRh

---
# Secret 5: Custom warning period
apiVersion: v1
kind: Secret
metadata:
  name: short-warning-secret
  namespace: default
  annotations:
    secret-operator.example.com/expires-at: "2025-06-15"
    secret-operator.example.com/warn-before: "1d"
  labels:
    managed-by: secret-operator
type: Opaque
data:
  token: dG9rZW4tMTIzNDU2Nzg5MA==
